name: Push Alma images

env:
  MAIN_BRANCH: "all-citus"
  PACKAGE_CLOUD_REPO_NAME: "citusdata/community-nightlies"
  PACKAGE_CLOUD_API_TOKEN: ${{ secrets.PACKAGE_CLOUD_API_TOKEN }}
  PACKAGING_PASSPHRASE: ${{ secrets.PACKAGING_PASSPHRASE }}
  PACKAGING_SECRET_KEY: ${{ secrets.PACKAGING_SECRET_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  DOCKERHUB_USER_NAME: ${{ secrets.DOCKERHUB_USER_NAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux-8-pg12
          - almalinux-8-pg13
          - almalinux-8-pg14
          - almalinux-8-pg15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This step is to fetch the images unanonymously to have higher bandwidth
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Publish Alma images
        run: |
          docker build -t citus/packaging:${{ matrix.image }} -f dockerfiles/${{ matrix.image }}/Dockerfile .
          docker tag citus/packaging:${{ matrix.image }} citus/packaging-test:${{ matrix.image }}
          docker push citus/packaging:${{ matrix.image }}
          docker push citus/packaging-test:${{ matrix.image }}

